Adding hootsuite
peviitor-ro/Scrapers-UI pull request #314
Opened 2023-11-26 19:02 UTC by DianaDascalu2

2023-11-26 19:46 UTC, lalalaurentiu requested changes

2023-11-26 19:46 UTC, lalalaurentiu commented on src/expressvpn/index.html
>                              <a href="#" target="_blank">
you forgot targetare.ro link
```suggestion
                            <a href="targetare.ro_link" target="_blank">
```

2023-11-26 19:46 UTC, lalalaurentiu commented on src/inthepocket/index.html
> +                            <a href="#" target="_blank">
you forgot targetare.ro link
```suggestion
                            <a href="targetare.ro_link" target="_blank">
```

2023-11-26 19:46 UTC, lalalaurentiu commented on src/qiagen/index.html
> +                            <a href="#" target="_blank">
you forgot targetare.ro like
```suggestion
                            <a href="targetare.ro_link" target="_blank">
```

2023-11-26 19:46 UTC, lalalaurentiu commented on src/sp/index.html
> +                            <img alt="sp"  src="None" />
you forgot image url
```suggestion
                            <img alt="sp"  src="image_url" />
```

2023-11-26 19:46 UTC, lalalaurentiu commented on src/sp/index.html
> +                            <a href="#" target="_blank">
you forgot targetare.ro link
```suggestion
                            <a href="targetare.ro_link" target="_blank">
```

2023-11-26 19:47 UTC, DianaDascalu2 commented on src/expressvpn/index.html
>                              <a href="#" target="_blank">
Got it.

2023-11-27 13:17 UTC, lalalaurentiu commented
@DianaDascalu2 You didn't have to accept my suggestions. In the 'href' attribute, you should search for links related to careers, targetare.ro, and add the image link.

2023-11-27 18:28 UTC, closed without merging